spring.application.name=product-services
server.port=8082
spring.data.mongodb.uri=mongodb://mongo:27017/productdb

eureka.client.service-url.defaultZone= http://eureka-server:8761/eureka/
eureka.instance.lease-renewal-interval-in-seconds= 30
eureka.instance.lease-expiration-duration-in-seconds= 90

